# Generated by Django 4.2.7 on 2025-09-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tuition', 'رسوم دراسية'), ('transport', 'رسوم نقل'), ('books', 'رسوم كتب'), ('uniform', 'رسوم زي موحد'), ('activities', 'رسوم أنشطة'), ('other', 'أخرى')], max_length=10, verbose_name='نوع الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(blank=True, max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], default='pending', max_length=10, verbose_name='الحالة')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='السنة الدراسية')),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المستحق')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المدفوع')),
                ('total_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المعلق')),
                ('total_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المتأخر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payment_summaries', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ملخص الدفعات',
                'verbose_name_plural': 'ملخصات الدفعات',
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
