# Generated by Django 4.2.7 on 2025-09-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, verbose_name='الفصل الدراسي')),
                ('midterm_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة منتصف الفصل')),
                ('final_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة النهائي')),
                ('practical_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة العملي')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='المجموع الكلي')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='النسبة المئوية')),
                ('grade_letter', models.CharField(default='F', max_length=2, verbose_name='الدرجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade_summaries', to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grade_summaries', to='subjects.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'ملخص الدرجات',
                'verbose_name_plural': 'ملخصات الدرجات',
                'unique_together': {('student', 'subject', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('midterm', 'امتحان منتصف الفصل'), ('final', 'امتحان نهائي'), ('practical', 'عملي'), ('quiz', 'اختبار قصير'), ('assignment', 'واجب')], max_length=10, verbose_name='نوع الامتحان')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة المحصلة')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة الكلية')),
                ('exam_date', models.DateField(verbose_name='تاريخ الامتحان')),
                ('remarks', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='subjects.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grades', to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'الدرجات',
                'unique_together': {('student', 'subject', 'exam_type', 'exam_date')},
            },
        ),
    ]
