# Generated by Django 4.2.7 on 2025-09-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز المادة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المادة')),
                ('grade', models.CharField(choices=[('1', 'الصف الأول'), ('2', 'الصف الثاني'), ('3', 'الصف الثالث'), ('4', 'الصف الرابع'), ('5', 'الصف الخامس'), ('6', 'الصف السادس'), ('7', 'الصف السابع'), ('8', 'الصف الثامن'), ('9', 'الصف التاسع'), ('10', 'الصف العاشر'), ('11', 'الصف الحادي عشر'), ('12', 'الصف الثاني عشر')], max_length=2, verbose_name='الصف')),
                ('subject_type', models.CharField(choices=[('core', 'مادة أساسية'), ('elective', 'مادة اختيارية'), ('activity', 'نشاط')], default='core', max_length=10, verbose_name='نوع المادة')),
                ('credit_hours', models.PositiveIntegerField(default=1, verbose_name='عدد الساعات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'unique_together': {('name', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, verbose_name='معلم أساسي')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'تعيين معلم - مادة',
                'verbose_name_plural': 'تعيينات المعلمين - المواد',
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفصل')),
                ('grade', models.CharField(choices=[('1', 'الصف الأول'), ('2', 'الصف الثاني'), ('3', 'الصف الثالث'), ('4', 'الصف الرابع'), ('5', 'الصف الخامس'), ('6', 'الصف السادس'), ('7', 'الصف السابع'), ('8', 'الصف الثامن'), ('9', 'الصف التاسع'), ('10', 'الصف العاشر'), ('11', 'الصف الحادي عشر'), ('12', 'الصف الثاني عشر')], max_length=2, verbose_name='الصف')),
                ('section', models.CharField(max_length=10, verbose_name='القسم')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='السعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='معلم الفصل')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'unique_together': {('grade', 'section')},
            },
        ),
    ]
