# Generated by Django 4.2.7 on 2025-09-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('elementary', 'ابتدائي'), ('middle', 'متوسط'), ('high', 'ثانوي')], default='elementary', max_length=10, verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='subject',
            name='assessment_method',
            field=models.TextField(blank=True, verbose_name='طريقة التقييم'),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('elementary', 'ابتدائي'), ('middle', 'متوسط'), ('high', 'ثانوي')], default='elementary', max_length=10, verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم المادة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='أهداف المادة'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='subjects.subject', verbose_name='المتطلبات السابقة'),
        ),
        migrations.AddField(
            model_name='subject',
            name='reference_books',
            field=models.TextField(blank=True, verbose_name='المراجع'),
        ),
        migrations.AddField(
            model_name='subject',
            name='textbook',
            field=models.CharField(blank=True, max_length=200, verbose_name='الكتاب المقرر'),
        ),
    ]
