# Generated by Django 4.2.7 on 2025-09-27 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('general', 'عام'), ('grade', 'درجة'), ('attendance', 'حضور'), ('payment', 'دفعة'), ('exam', 'امتحان'), ('event', 'فعالية'), ('announcement', 'إعلان')], max_length=15, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجدول')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال المجدول')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('recipients', models.ManyToManyField(related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستقبلون')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('title_template', models.CharField(max_length=200, verbose_name='قالب العنوان')),
                ('message_template', models.TextField(verbose_name='قالب الرسالة')),
                ('notification_type', models.CharField(choices=[('general', 'عام'), ('grade', 'درجة'), ('attendance', 'حضور'), ('payment', 'دفعة'), ('exam', 'امتحان'), ('event', 'فعالية'), ('announcement', 'إعلان')], max_length=15, verbose_name='نوع الإشعار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('read', 'تم القراءة'), ('failed', 'فشل الإرسال')], max_length=20, verbose_name='حالة التسليم')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification', verbose_name='الإشعار')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستقبل')),
            ],
            options={
                'verbose_name': 'سجل الإشعار',
                'verbose_name_plural': 'سجلات الإشعارات',
                'unique_together': {('notification', 'recipient')},
            },
        ),
    ]
