# Generated by Django 4.2.7 on 2025-09-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأيام')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='أيام الحضور')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='أيام الغياب')),
                ('late_days', models.PositiveIntegerField(default=0, verbose_name='أيام التأخير')),
                ('excused_days', models.PositiveIntegerField(default=0, verbose_name='أيام الغياب بعذر')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الحضور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_summaries', to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendance_summaries', to='subjects.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'ملخص الحضور',
                'verbose_name_plural': 'ملخصات الحضور',
                'unique_together': {('student', 'subject', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'غياب بعذر')], max_length=10, verbose_name='الحالة')),
                ('remarks', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendance', to='subjects.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'الحضور والغياب',
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
