# Generated by Django 4.2.7 on 2025-09-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='remarks',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('regular', 'عادي'), ('exam', 'امتحان'), ('activity', 'نشاط'), ('field_trip', 'رحلة مدرسية')], default='regular', max_length=15, verbose_name='نوع الحضور'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الحضور'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف'),
        ),
    ]
